name: what4-domains CI
on:
  - push
  - pull_request

env:
  CACHE_VERSION: 4

jobs:
  linux:
    name: GHC-${{ matrix.ghc }}
    runs-on: ubuntu-24.04
    continue-on-error: false
    strategy:
      matrix:
        ghc:
          - "9.12.2"
          - "9.10.1"
          - "9.8.1"
          - "9.6.2"
          - "9.4.4"
          - "9.2.2"
          - "9.0.2"
          - "8.10.7"
          - "8.8.4"
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: false

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-21.11
          install_url: https://releases.nixos.org/nix/nix-2.11.0/install
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v17
        with:
          name: galois
          authToken: '${{ secrets.CACHIX_WHAT4 }}'

      - uses: actions/cache/restore@v5
        name: Restore cabal store cache
        id: cache
        env:
          key: ${{ env.CACHE_VERSION }}-cabal-ubuntu-24.04-ghc${{ matrix.ghc }}
        with:
          path: |
            ~/.cabal/store
            ~/.local/state/cabal/store
            dist-newstyle
          key: |
            ${{ env.key }}-${{ github.ref }}
          restore-keys: |
            ${{ env.key }}-

      - name: Setup Environment Vars
        run: |
          GHC=haskell.compiler.ghc$(echo ${{ matrix.ghc }} | sed -e s,\\.,,g)
          case ${{ matrix.ghc }} in
            9.0.2) GHC_NIXPKGS=github:nixos/nixpkgs/nixos-22.05 ;;
            9.2.2) GHC_NIXPKGS=github:nixos/nixpkgs/nixos-22.05 ;;
            9.4.4) GHC_NIXPKGS=github:nixos/nixpkgs/nixos-23.05 ;;
            9.6.2) GHC_NIXPKGS=github:nixos/nixpkgs/nixos-23.05 ;;
            9.8.1) GHC_NIXPKGS=github:nixos/nixpkgs/nixos-23.11 ;;
            9.10.1) GHC_NIXPKGS=github:nixos/nixpkgs/nixos-24.05 ;;
            9.12.2) GHC_NIXPKGS=github:nixos/nixpkgs/nixos-25.05 ;;
            *)     GHC_NIXPKGS=github:nixos/nixpkgs/21.11 ;;
          esac
          echo "GHC_NIXPKGS=${GHC_NIXPKGS}" >> $GITHUB_ENV
          echo NS="nix shell ${GHC_NIXPKGS}#pkg-config ${GHC_NIXPKGS}#cabal-install ${GHC_NIXPKGS}#${GHC} ${GHC_NIXPKGS}#gmp ${GHC_NIXPKGS}#zlib ${GHC_NIXPKGS}#zlib.dev" >> $GITHUB_ENV

      - name: Cabal update
        shell: bash
        run: $NS -c cabal update

      - name: Cabal check
        shell: bash
        run: |
          cd what4-domains && $NS -c cabal check

      - name: Build
        shell: bash
        run: $NS -c cabal build pkg:what4-domains

      - name: Test
        shell: bash
        run: $NS -c cabal test pkg:what4-domains

      - name: Documentation
        shell: bash
        run: $NS -c cabal haddock what4-domains

      - uses: actions/cache/save@v5
        name: Save cabal store cache
        if: always()
        with:
          path: |
            ~/.cabal/store
            ~/.local/state/cabal/store
            dist-newstyle
          key: ${{ steps.cache.outputs.cache-primary-key }}

      - name: Package's Cabal/GHC compatibility
        shell: bash
        run: |
          defsetup()  { echo import Distribution.Simple; echo main = defaultMain; }
          setup_src() { if [ ! -f Setup.hs ] ; then defsetup > DefSetup.hs; fi; ls *Setup.hs; }
          setup_bin() { echo setup.${{ matrix.ghc }}; }
          with_ghc()  { $NS -c ${@}; }
          (cd what4-domains; with_ghc ghc -o $(setup_bin) $(setup_src) && ./$(setup_bin) clean)
